# Generated by Django 3.1.3 on 2020-11-30 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(choices=[('m', 'Married'), ('d', 'Divorce'), ('w', 'Widowed'), ('s', 'Single')], max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='upload')),
                ('note', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('workplace', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=120)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.address')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': "Member's",
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('marital_status', models.CharField(choices=[('m', 'Married'), ('d', 'Divorce'), ('w', 'Widowed'), ('s', 'Single')], max_length=1)),
                ('date', models.DateField()),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('workplace', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('f', 'First Time Visitor'), ('r', 'Returning Visitor')], max_length=1)),
                ('reason', models.CharField(choices=[('c', 'Would like to know more about the Church'), ('m', 'Would like to be a member'), ('v', 'Would like a Visit'), ('a', 'New to area'), ('b', 'Would like to know more being a Christian')], max_length=1)),
                ('note', models.TextField(blank=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.address')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event')),
                ('guest_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('received_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': "Visitor's",
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.PositiveIntegerField()),
                ('women', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('visitors', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
        ),
    ]
