# Generated by Django 3.1.4 on 2020-12-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20201213_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='received_by',
        ),
    ]
