# Generated by Django 3.1.4 on 2020-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'contribution', 'verbose_name_plural': 'contribution'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donation'},
        ),
        migrations.AddField(
            model_name='tithe',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=9),
        ),
    ]
