# Generated by Django 3.1.3 on 2020-11-30 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('event_type', models.CharField(choices=[('Business Talk', 'Business Talk'), ('Relationship', 'Relationship'), ('Training', 'Training'), ('Conference', 'Conference'), ('Wedding', 'Wedding'), ('Child Dedication', 'Child Dedication'), ('Church Service', 'Church Service'), ('Prayer Time', 'Prayer Time'), ('Music Festival', 'Music Festival')], max_length=25)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
