# Generated by Django 3.1.4 on 2020-12-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20201212_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_role', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Membership Roles',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.group')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('member_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='group.memrole')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(through='group.GroupMember', to='member.Member'),
        ),
    ]
