# Generated by Django 3.1.3 on 2020-11-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_role', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Membership Roles',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('member_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='group.memrole')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(through='group.GroupMember', to='member.Member'),
        ),
    ]
