# Generated by Django 3.1.3 on 2020-11-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=250)),
                ('sub_name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=250)),
                ('branch_pastor', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to=None)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
