# Generated by Django 3.1.3 on 2020-11-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_address', models.CharField(blank=True, max_length=15)),
                ('postal_address', models.CharField(blank=True, max_length=30)),
                ('house_number', models.CharField(blank=True, max_length=15)),
                ('town', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
            },
        ),
    ]
