# Generated by Django 3.1.4 on 2020-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sms_id',
            field=models.CharField(default='qwert', max_length=150),
            preserve_default=False,
        ),
    ]
