# Generated by Django 3.1.4 on 2020-12-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_sms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='via',
            field=models.CharField(max_length=50),
        ),
    ]
